repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
  - repo: local
    hooks:
      - id: ruff
        name: ruff check
        entry: uv run ruff check --fix
        language: system
        types: [python]
      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types: [python]

  - repo: local
    hooks:
      - id: ty
        name: ty check
        entry: uvx ty check
        language: system
        types: [python]
        pass_filenames: false

  # - repo: https://github.com/RodrigoGonzalez/check-mkdocs
  #   rev: v1.2.0
  #   hooks:
  #     - id: check-mkdocs
  #       name: check-mkdocs
  #       args: ["--config", "mkdocs.yml"] # Optional, mkdocs.yml is the default
  #       # If you have additional plugins or libraries that are not included in
  #       # check-mkdocs, add them here
  #       additional_dependencies: ["mkdocs-material"]
